Migrate all SelectableText to SelectionArea.
flutter/gallery pull request #699
Opened 2022-05-26 16:06 UTC by olegzaim

Replaced all SelectableText to SelectionArea.
See [flutter/gallery#698](https://github.com/flutter/gallery/issues/698)

2022-05-26 16:14 UTC, guidezpl requested changes
This is not quite what is required. Only ~5 `SelectionArea`s should be necessary, one per `MaterialApp`, and one for the setting page, each placed near the top of the widget tree.

Each `SelectableText` should be replaced by `Text`.

2022-05-30 08:27 UTC, guidezpl commented on lib/studies/shrine/app.dart
>              ShrineApp.loginRoute: (context) => const LoginPage(),
should work on the login page as well

2022-05-30 08:27 UTC, guidezpl commented on lib/studies/shrine/app.dart
> +            ShrineApp.homeRoute: (context) => SelectionArea(child: home),
is there an `ApplyTextOptions` missing here? if not, can it be moved here for consistency?

2022-05-31 06:53 UTC, olegzaim commented
> * Rally text selection is invisible.

Hello, there is something wrong with the cursor for selection area because when I select all area it isn't invisible, but when I just tap and press it is stay invisible: 
- Single select with long press
![long press for select](https://user-images.githubusercontent.com/35899176/171108829-70ccd993-a9b9-48aa-ab17-77d66fee4ba7.jpg)
- Select all
![select all](https://user-images.githubusercontent.com/35899176/171108842-f9ea79c5-a020-423f-afd6-1fade793d755.jpg)

> * Demos don't have text selection

Is it enough or it's need to be selectable also inside demos?
![home and demos select](https://user-images.githubusercontent.com/35899176/171109156-5d8ea8db-ac08-457e-b14d-1f6876dd0da9.jpg)

2022-05-31 08:21 UTC, guidezpl commented
I made some small fixes for consistency. The only thing missing I think is adding selection for the demos (material, cupertino, etc.)

2022-05-31 08:25 UTC, olegzaim commented
> I made some small fixes for consistency. The only thing missing I think is adding selection for the demos (material, cupertino, etc.)

Okay, great thank you :)

2022-06-03 07:27 UTC, guidezpl approved these changes
Thanks for contributing!

2022-06-08 10:34 UTC, guidezpl commented
@chunhtai This change triggers errors that cause  benchmark and golden tests to fail, would appreciate you taking a look if possible.

2022-06-29 17:38 UTC, guidezpl commented
@olegzaim Could you take a look at the merge conflicts so that we can land this? Thanks!

2022-06-29 17:39 UTC, guidezpl commented
Realized you might only have access to @OlegZaimNLT, if so, please create a new PR cloning this branch

2022-06-30 09:01 UTC, OlegZaimNLT commented
Hey @guidezpl I can't merge because it says that I don't have permissions
![Screenshot 2022-06-30 at 11 59 16](https://user-images.githubusercontent.com/106600432/176637276-42a09438-4665-494e-b024-ca8436a2347b.png)
.

2022-06-30 14:49 UTC, closed without merging