Optimizations: Foreach replaced by indexed loops
flutter/gallery pull request #954
Opened 2023-05-28 04:10 UTC by feliperussi

## Description

The changes included in this pull request are suggestions to modify some parts of the code to optimize it. Looking through the source code, we identified some for each method that could be easily changed to indexed loops to ensure optimization for the code and reduce possible security and memory risks. 

## Issues
Fixes #

In lib/demos/material/tabs_demo.dart:

Old method with forEach:
![image](https://github.com/flutter/gallery/assets/55710547/6c91f490-90f3-44ec-9afc-7e85f60d3072)

New method with indexed loop:
   
```
   Widget build(BuildContext context) {
    final localizations = GalleryLocalizations.of(context)!;
    final tabs = [
      localizations.colorsRed,
      localizations.colorsOrange,
      localizations.colorsGreen,
    ];

    List<Tab> tabWidgets = [];
    List<Text> tabCenters = [];

    for (int i = 0; i < tabs.length; i++) {
      tabWidgets.add(Tab(text: tabs[i]));
      tabCenters.add(Text(tabs[i]));
    }

    return Scaffold(
      appBar: AppBar(
        automaticallyImplyLeading: false,
        title: Text(
          localizations.demoTabsNonScrollingTitle,
        ),
        bottom: TabBar(
          controller: _tabController,
          isScrollable: false,
          tabs: tabWidgets,
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: tabCenters,
      ),
    );
  }
```

In lib/routes.dart:

Old method with forEach:
![image](https://github.com/flutter/gallery/assets/55710547/63df5237-9dc7-4135-8664-818449bafe5d)

New method with indexed loop:
```
static Route<dynamic>? onGenerateRoute(RouteSettings settings) {
  for (int i = 0; i < paths.length; i++) {
    final path = paths[i];
    final regExpPattern = RegExp(path.pattern);
    if (regExpPattern.hasMatch(settings.name!)) {
      final firstMatch = regExpPattern.firstMatch(settings.name!)!;
      final match = (firstMatch.groupCount == 1) ? firstMatch.group(1) : null;
      if (kIsWeb) {
        return NoAnimationMaterialPageRoute<void>(
          builder: (context) => path.builder(context, match),
          settings: settings,
        );
      }
      if (path.openInSecondScreen) {
        return TwoPanePageRoute<void>(
          builder: (context) => path.builder(context, match),
          settings: settings,
        );
      } else {
        return MaterialPageRoute<void>(
          builder: (context) => path.builder(context, match),
          settings: settings,
        );
      }
    }
  }

  // If no match was found, we let [WidgetsApp.onUnknownRoute] handle it.
  return null;
}
```

In lib/studies/shrine/app.dart:

Old method with forEach:
![image](https://github.com/flutter/gallery/assets/55710547/a3094087-60d9-4d63-8f8b-bc9c19c3dd7b)

New method with indexed loop:

```
AppStateModel fromPrimitives(Object? data) {
  final appState = AppStateModel()..loadProducts();
  final appData = Map<String, dynamic>.from(data as Map);

  // Reset selected category.
  final categoryIndex = appData['category_index'] as int;
  appState.setCategory(categories[categoryIndex]);

  // Reset cart items.
  final cartItems = appData['cart_data'] as Map<dynamic, dynamic>;
  final cartEntries = cartItems.entries.toList();
  for (int i = 0; i < cartEntries.length; i++) {
    dynamic id = cartEntries[i].key;
    dynamic quantity = cartEntries[i].value;
    appState.addMultipleProductsToCart(id as int, quantity as int);
  }

  return appState;
}
```

After suggesting those changes, the app continues to function as before. We hope that they are well received by the community. This app is really useful!
---

>**Note**: Please find the development and releasing instructions at https://github.com/flutter/gallery#development

2023-05-28 05:24 UTC, domesticmouse commented
Please sign the CLA. We can't land the PR without it =)

2023-05-28 05:29 UTC, domesticmouse requested changes

2023-05-28 05:29 UTC, domesticmouse commented on lib/demos/material/tabs_demo.dart
> -          tabs: [
Please revert this change.

2023-05-28 05:29 UTC, domesticmouse commented on lib/routes.dart
> +    for (int i = 0; i < paths.length; i++) {
What is the intent of this change? The previous code is clearer in intent, and avoids potential off by one errors.

2023-05-28 05:29 UTC, domesticmouse commented on lib/demos/material/tabs_demo.dart
> -        children: [
Please revert this change.

2023-05-28 05:29 UTC, domesticmouse commented on lib/studies/shrine/app.dart
> +    final cartEntries = cartItems.entries.toList();
Please use `for (final cart in cartItems) { ... }` as this approach is verbose and error prone.

2023-05-28 05:29 UTC, domesticmouse commented on lib/studies/shrine/app.dart
> +      dynamic id = cartEntries[i].key;
I'd be tempted to use Dart 3 destructing here.

2023-08-01 17:54 UTC, Hixie commented
@feliperussi Will you be able to continue working on this? It's totally fine if not; we can take it over (though it might take longer). I'm just asking because I'm trying to clean out our review queue.

2023-09-12 22:59 UTC, Hixie commented
I'm going to close this as it looks like it is no longer being worked on.

2023-09-12 22:59 UTC, closed without merging